name: run aoc 2024 tests

on:
  push:
    paths:
      - "day*/**"
      - ".github/workflows/**"
      - "!template/**"
  workflow_dispatch:

jobs:
  run_all_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Install zsh
        run: sudo apt-get update; sudo apt-get install zsh

      - name: checkout repository
        uses: actions/checkout@v4

      - name: run all tests
        run: |
          echo "Running tests for aoc 2024 🎅"
          make test-all
        shell: zsh {0}
